name: Build and Publish to AWS ECR.

on:
  push:
    branches:
      - master

jobs:

  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          docker login --username ${{ secrets.ECR_USERNAME }} --password ${{ secrets.ECR_PASSWORD }} ${{ secrets.ECR_REGISTRY }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
            docker build -t $ECR_REGISTRY:$IMAGE_TAG .
            docker push $ECR_REGISTRY:$IMAGE_TAG
            echo "image=$ECR_REGISTRY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: bolan-test-project-revision2.json
          container-name: bolan-test-project-container
          image: ${{ steps.build-image.outputs.image }}
    
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service-name: bolan-test-project-service
          cluster-name: bolan-test-project
          wait-for-service-stability: true